ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'CHECKED_IN';
ALTER TYPE "PaymentMethodType" ADD VALUE IF NOT EXISTS 'CASH';

ALTER TABLE "bookings"
ADD COLUMN IF NOT EXISTS "checkedInAt" TIMESTAMP(3);
